name: gitleaks

on: [push,pull_request]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@master
      with:
        config-path: security/.gitleaks.toml
    
    - name: Check out
      uses: actions/checkout@v2

    - name: Install yq
      run: |
        sudo wget -LO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/3.3.0/yq_linux_amd64
        sudo chmod +x /usr/local/bin/yq
    - name: Generate
      run: |
        ./generate.sh -o samples/gcp.md -i https://github.com/devu-62442/actions-dashboard/blob/master/samples/some-other-gcp-repos
        
        if [ -z "$(git status -s -- samples/gcp.md)" ]; then
          echo No changes to commit 
          exit 0
        fi
        git config user.email "devyani.vij2495@gmail.com"
        git config user.name "devu-62442"
        git add samples/gcp.md
        git commit -m "Update dashboard markdown"
        git push origin master
